theme: minima
<<<<<<< HEAD
title: Mathew's Tech Lab
description: Documenting my home lab and IT projects
=======
title: "Home"
description: "Welcome to my personal website where I showcase my projects and interests."
>>>>>>> db2d300 (fixed config/index, made my first post)
